controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 30.0
     # You can set this higher than the controller manager update rate, but it will be throttled
    
    base_frame_id: base_link

    left_wheel_names: ['left_back_wheel_joint', 'left_front_wheel_joint']
    right_wheel_names: ['right_back_wheel_joint', 'right_front_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 0.3950
    wheel_radius: 0.07

    use_stamped_vel: false